# Dependencies
markdown:         
highlighter:      rouge

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            x3tb3t
tagline:          'offsec'
description:      'Hacking stuff. <a href="#" target="_blank">x3tb3t@protonmail.com</a>.'
url:              https://x3tb3t.github.io
baseurl:          /

author:
  name:           'x3tb3t'
  url:            https://x3tb3t.github.io

paginate:         5

# Custom vars
version:          

github:
  repo:           https://github.com/x3tb3t
